Vagrant.configure("2") do |config|
  # Используем образ Ubuntu 18.04
  config.vm.box = "ubuntu/bionic64"

  # Установим python3 и python3-pip
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y python3 python3-pip"

  # Установим Python-библиотеки psycopg2 и Django
  config.vm.provision "shell", inline: "pip3 install psycopg2 Django"

  # Копируем пустой файл на файловую систему гостевой машины
  config.vm.provision "file", source: "empty_file.txt", destination: "/vagrant/empty_file.txt"
end
